parameters:
  name: bdb_swp_to_vwc
  db_path: C:\Users\u0143591\OneDrive - KU Leuven\research_data\BDB\processed\pear_database.db
  query_path: queries/bdb_data.sql
  data:
    fill_missing:
      pruning_treatment: NRP
      irrigation_treatment: FI
      irrigation_amount: 0.0
    group_id_cols:
      - orchard_id
      - plot_id
      - depth_cm
      - measurement_year
    pivot: true
    train_cutoff: "2009"
    date_col: measurement_date
    target_col: swp_mpa
    standardize_cols:
      - avg_moist_30
      - avg_moist_60
      - avg_moist_90
      - avg_soil_temp_30
      - ETo
      - swp_mpa
      - precip_daily
      - irrigation_amount
    dummies:
      - composite_group_id
      - pruning_treatment
      - irrigation_treatment
    vg_parameters:
      bierbeek:
        alpha: 0.005
        theta_s: 0.42
        theta_r: 0.11
        n: 1.70
      meensel:
        alpha: 0.011
        theta_s: 0.45
        theta_r: 0.15
        n: 1.47
      sint_truiden:
        alpha: 0.015
        theta_s: 0.50
        theta_r: 0.06
        n: 1.40
